# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# Actual Budget — FreeBSD daemonless container
# Self-hosted personal-finance sync server; serves its bundled web client as
# static files from the same Node process (not the Electron desktop app).
# Upstream: https://github.com/actualbudget/actual  (MIT)
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
ARG ACTUAL_VERSION=v26.9.0

# ==========================================================================
# Stage 1: Builder
# ==========================================================================
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

ARG ACTUAL_VERSION

# Build dependencies.
#  - node24: engines.node requires >=22.18.0; upstream itself builds on
#    node:24-bookworm. Already on FreeBSD's `quarterly` branch (verified
#    against the live packagesite), so no /quarterly -> /latest switch is
#    needed here. Yarn is invoked from the vendored release below, not via
#    npm/corepack, so neither package is installed.
#  - git-lite: clones the pinned tag; bin/package-browser (below) also shells
#    out to git to pull translations.
#  - bash: bin/package-browser has a `#!/bin/bash` shebang; FreeBSD ships no
#    /bin/bash by default.
#  - FreeBSD-clang/-lld/-toolchain/-clibs-dev, pkgconf, python3, gmake:
#    node-gyp toolchain. argon2, bcrypt and better-sqlite3 all compile from
#    source on FreeBSD — none has a prebuilt. node-gyp itself comes in via
#    yarn's own dependency tree (yarn.lock: node-gyp@npm:^11.2.0), not npm.
RUN pkg install -y \
      node24 \
      git-lite bash \
      FreeBSD-clang FreeBSD-lld FreeBSD-toolchain FreeBSD-clibs-dev \
      pkgconf python3 gmake \
    && pkg clean -ay

# FreeBSD's bash package only installs to /usr/local/bin.
RUN ln -s /usr/local/bin/bash /bin/bash

WORKDIR /app
RUN git clone --depth 1 --branch ${ACTUAL_VERSION} \
      https://github.com/actualbudget/actual.git .

# Yarn 4 (berry) is vendored in the repo at .yarn/releases — FreeBSD's `yarn`
# package is 1.22 (Classic) and can't read this repo's .yarnrc.yml at all, so
# invoke the vendored release directly everywhere below. Resolved by glob
# rather than hardcoding the filename: upstream bumps the vendored yarn
# version between releases, and a hardcoded `yarn-4.17.1.cjs` would silently
# stop matching on the next bump (loud failure, but an avoidable one — see
# .yarnrc.yml's own `yarnPath` for the source of truth).
RUN ln -s "$(pwd)/$(ls .yarn/releases/yarn-*.cjs)" /usr/local/bin/yarn-vendored.cjs
ENV YARN="node /usr/local/bin/yarn-vendored.cjs"

# dependenciesMeta re-enables build/postinstall scripts (enableScripts:false
# is the repo-wide default) for exactly six packages. Two of them are not
# reachable from the workspaces this port ships and have no FreeBSD path:
#  - electron (desktop-electron only): its install.js unconditionally
#    downloads a platform artifact with no FreeBSD build ever published — a
#    hard failure, not a fallback.
#  - sharp (0.32.6, confirmed via yarn.lock to be pulled in only by the
#    Docusaurus `docs` site, nothing this port ships): no FreeBSD prebuilt.
# Both are out of scope per PORT-BRIEF anyway (desktop app / docs site). A
# whole-monorepo `yarn install` (matching upstream, needed so root-only
# devDependencies like `lage` are present) would otherwise try to run both.
RUN node -e " \
    const fs = require('fs'); \
    const p = JSON.parse(fs.readFileSync('package.json', 'utf8')); \
    for (const dep of ['electron', 'sharp']) { \
      if (!(dep in (p.dependenciesMeta || {}))) { \
        console.error('PATCH DRIFT: dependenciesMeta.' + dep + ' missing — review the electron/sharp skip patch'); \
        process.exit(1); \
      } \
      delete p.dependenciesMeta[dep]; \
    } \
    fs.writeFileSync('package.json', JSON.stringify(p, null, 2) + '\n'); \
    console.log('Disabled electron + sharp postinstall (no FreeBSD path, out of scope per PORT-BRIEF).'); \
    "

# lage (the monorepo build orchestrator `yarn build:server` depends on)
# requires('glob-hasher') unconditionally at module load, in its internal
# task-hashing code. glob-hasher is a NAPI addon with no freebsd-x64
# optionalDependency published and no source build published either — a
# hard, uncatchable crash before lage runs a single task, unrelated to
# anything this port ships. See patches/glob-hasher-shim/index.js for the
# pure-JS stand-in and why it's safe (lage's cache starts empty on every
# build here regardless).
COPY patches/glob-hasher-shim ./patches/glob-hasher-shim

# Same problem, second tool: several workspaces' "build" scripts (e.g.
# @actual-app/crdt, @actual-app/core) end with `tsgo -b` to emit .d.ts
# declarations via Microsoft's experimental native (Go-compiled) TypeScript
# compiler. It has no FreeBSD binary published (win32/darwin/linux
# optionalDependencies only) and its JS wrapper throws unconditionally when
# none is found. None of this port's build path needs the declarations it
# emits — every workspace it touches resolves cross-package imports straight
# from .ts source via `exports` (verified for crdt and loot-core) — so a
# no-op stand-in is safe. See patches/tsgo-shim/bin/tsgo.js.
COPY patches/tsgo-shim ./patches/tsgo-shim

# COPY itself would already fail if either shim file were missing from the
# build context — this only exists as a plain, greppable sanity check.
RUN test -f patches/glob-hasher-shim/index.js && test -f patches/tsgo-shim/bin/tsgo.js

# Drift guard for both shims — checks the actual assumptions each one
# depends on, not just "did the COPY above land" (which COPY already
# guarantees on its own):
#  - glob-hasher's resolved version in yarn.lock is still a 1.x, matching the
#    API surface patches/glob-hasher-shim/index.js implements (read from the
#    real package's shipped index.d.ts, not guessed) — a 2.x could change
#    function signatures.
#  - @typescript/native-preview is still resolved at all (if upstream drops
#    tsgo entirely, the shim is dead weight worth removing).
#  - @actual-app/crdt and @actual-app/core still resolve their cross-package
#    imports to `.ts` source rather than built `dist/`/`lib-dist/` output —
#    the one fact that makes no-opping tsgo's declaration output safe. This
#    is the load-bearing check: if it ever fails, the shim itself is wrong,
#    not just stale.
RUN node -e " \
    const fs = require('fs'); \
    const lock = fs.readFileSync('yarn.lock', 'utf8'); \
    const ghMatch = lock.match(/glob-hasher@npm:[^\"]*\":\n  version: (\S+)/); \
    if (!ghMatch || !ghMatch[1].startsWith('1.')) { \
      console.error('PATCH DRIFT: glob-hasher resolved to ' + (ghMatch && ghMatch[1]) + ', not the 1.x API patches/glob-hasher-shim implements — review the shim'); \
      process.exit(1); \
    } \
    if (!lock.includes('@typescript/native-preview@npm:')) { \
      console.error('PATCH DRIFT: @typescript/native-preview no longer in yarn.lock — the tsgo shim/resolution can be dropped'); \
      process.exit(1); \
    } \
    const allowedDistPaths = new Set(['./lib-dist/electron/bundle.desktop.js']); \
    for (const file of ['packages/crdt/package.json', 'packages/loot-core/package.json']) { \
      const pkg = JSON.parse(fs.readFileSync(file, 'utf8')); \
      for (const val of Object.values(pkg.exports || {})) { \
        const values = typeof val === 'string' ? [val] : Object.values(val); \
        for (const v of values) { \
          if (typeof v === 'string' && (v.includes('/dist/') || v.includes('/lib-dist/')) && !allowedDistPaths.has(v)) { \
            console.error('PATCH DRIFT: ' + file + ' now exports built output (' + v + '), not source — the tsgo no-op shim is no longer safe, see .porting/cookbook.md'); \
            process.exit(1); \
          } \
        } \
      } \
    } \
    console.log('glob-hasher/tsgo shim assumptions verified against yarn.lock and workspace exports.'); \
    "

RUN node -e " \
    const fs = require('fs'); \
    const p = JSON.parse(fs.readFileSync('package.json', 'utf8')); \
    p.resolutions = Object.assign({}, p.resolutions, { \
      'glob-hasher': 'portal:./patches/glob-hasher-shim', \
      '@typescript/native-preview': 'portal:./patches/tsgo-shim', \
    }); \
    fs.writeFileSync('package.json', JSON.stringify(p, null, 2) + '\n'); \
    console.log('Resolved glob-hasher and @typescript/native-preview to their FreeBSD shims.'); \
    "

RUN $YARN install

# Upstream caps the build heap at 8 GB via NODE_OPTIONS; this build host has
# ~9 GB usable and runs other services, so start conservative (per
# PORT-BRIEF) and only raise this if a build OOMs.
ENV NODE_OPTIONS=--max_old_space_size=4096

# lage's task hasher runs `git ls-tree HEAD` during init. Upstream's own
# Dockerfile seeds a throwaway git repo for this because it COPYs individual
# files rather than cloning, so it has no .git at all. This stage cloned the
# real tag above, so a valid git repo with a checked-out commit already
# exists — no seed commit needed.
RUN $YARN build:server

# Trim the full install down to sync-server's production deps only (mirrors
# upstream's own Dockerfile exactly).
RUN $YARN workspaces focus @actual-app/sync-server --production

# @actual-app/web and @actual-app/sync-server are workspace symlinks into the
# monorepo tree. Replace @actual-app/web with just its built static assets +
# manifest (upstream does the same); the sync-server self-symlink is dropped
# since the server is copied to the runtime image by build output, not as an
# installed dependency of itself.
RUN rm -rf ./node_modules/@actual-app/web ./node_modules/@actual-app/sync-server && \
    mkdir -p ./node_modules/@actual-app/web && \
    cp packages/desktop-client/package.json ./node_modules/@actual-app/web/package.json && \
    cp -r packages/desktop-client/build ./node_modules/@actual-app/web/build

RUN echo "${ACTUAL_VERSION}" > /tmp/app_version

# ==========================================================================
# Stage 2: Runtime
# ==========================================================================
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG ACTUAL_VERSION
ARG PACKAGES="node24 ca_root_nss"
ARG HEALTHCHECK_ENDPOINT="http://localhost:5006/health"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

LABEL org.opencontainers.image.title="Actual Budget" \
      org.opencontainers.image.description="Self-hosted personal finance sync server (Actual Budget) on FreeBSD" \
      org.opencontainers.image.source="https://github.com/daemonless/actual" \
      org.opencontainers.image.url="https://actualbudget.org/" \
      org.opencontainers.image.version="${ACTUAL_VERSION}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Productivity" \
      io.daemonless.port="5006" \
      io.daemonless.volumes="/data" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.packages="${PACKAGES}"

# ca_root_nss: bank-sync providers (GoCardless/SimpleFIN/Pluggy/Akahu/
# EnableBanking) are reached over HTTPS when an operator configures them.
# Out of scope to configure here, but the runtime needs the CA bundle present
# regardless of whether a given deployment uses them.
RUN pkg install -y ${PACKAGES} && \
    mkdir -p /app /data && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

COPY --from=builder --chown=bsd:bsd /tmp/app_version /app/version
COPY --from=builder --chown=bsd:bsd /app/node_modules /app/node_modules
COPY --from=builder --chown=bsd:bsd /app/packages/sync-server/package.json /app/package.json
COPY --from=builder --chown=bsd:bsd /app/packages/sync-server/build /app/build

# /app is fully covered by --chown above; /data is created by the pkg-install
# RUN before any COPY, so it still needs its own chown (mkdir -p defaults to
# root:wheel).
RUN chown -R bsd:bsd /data

COPY root/ /
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* /healthz

WORKDIR /app

# ACTUAL_HOSTNAME defaults to '::' (IPv6-any) in load-config.js; in a
# container without working IPv6 the listener binds v6-only while looking
# healthy, and 127.0.0.1 gets connection-refused. Force it to 0.0.0.0.
ENV NODE_ENV=production \
    ACTUAL_PORT=5006 \
    ACTUAL_HOSTNAME=0.0.0.0 \
    ACTUAL_DATA_DIR=/data

EXPOSE 5006

VOLUME /data